WEB-339: (-) initializing/instantiating modules in beforeEach()
- getting multiple errors in help-menu
```
Error: [$injector:modulerr] Failed to instantiate module helpMenuTopbar due to:
[$injector:modulerr] Failed to instantiate module ngMaterial due to:
[$injector:nomod] Module 'ngMaterial' is not available!
```

- and an unknown reference in unpaywall to 'bulibUnpaywallProvider'
```
Error: [$injector:unpr] Unknown provider: bulibUnpaywallProvider <- bulibUnpaywall
```